### ISSUE TITLE
Change naming of time parameters

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/dune-alerts#45]
Some queries have changed their naming convention to `start_time` and `end_time`. This means that they are not compatible with this code anymore since it uses the convention `StartTime` and `EndTime`.

https://github.com/cowprotocol/dune-alerts/blob/0a4669bad86111e15886189b21dcadc65ac792a1/src/models.py#L52-L53

It is probably enough to change all queries to follow that new convention and change the hard-coded parameters in this repo.

Some context: At the moment it is not possible to use query views inside other queries if parameters have capital letters. Therefore we switched to an underscore convention. In principle it would be possible to have special queries with the old naming convention for alerts following a different convention. Those queries are separate queries anyways due to additional filtering. Midterm that will probably too confusing though.

cc @harisang

**Comment by harisang** [comment]
> It is probably enough to change all queries to follow that new convention and change the hard-coded parameters in this repo.

Yes, let's do that.
